apiVersion: backstage.io/v1alpha1
kind: API
metadata: 
  annotations: 
    backstage.io/techdocs-ref: "dir:."
  description: "The encoded"
  links: 
    - 
      icon: github
      title: "GitHub Repo"
      url: "https://github.com/masagaribhai/Backstage-API-Templates"
    - 
      icon: code
      title: "API Spec"
      url: "https://github.com/masagaribhai/Backstage-API-Templates/blob/main/todo.yaml"
  name: urlencoded
  tags: 
    - node
    - dot-net-core-web-api
spec: 
  definition: |
      openapi: 3.0.2
      info:
        title: WebAPI
        description: This is the sample web api
        x-app-prefix: xyz
        x-bitbucket-repourl: http://www.deloitte.com
        x-buildplaykey: test
        version: 'Core'
        contact:
             name: Dummy
             email: xyz@xyz.com
             url: http://www.deloitte.com
        x-apmnumber: 123
        x-vanguard-service-type: Core
        x-vanguard-product-family: Tech Support
        x-slo-urls: 
             - https://www.deloitte.com
             - https://www.vanguard.com
      servers:
        - url: https://webapi20220913163904.azurewebsites.net/
      paths:
        /todoitems:
          get:
            tags:
              - Todo 
            responses:
              '200':
                description: Success
          post:
            requestBody:
              required: true
              content:
                application/x-www-form-urlencoded:
                  schema:
                    type: object
                    properties:
                      name:         
                        type: string
                      id:
                        type: integer
                      isComplete:
                        type: boolean
                    required:
                      - name
                      - id
                      - isComplete
            responses:
              '200':
                description: OK
        /todoitems/complete:
          get:
            tags:
              - Todo
            responses:
              '200':
                description: Success
        '/todoitems/{id}':
          get:
            summary: Returns a list of users.
            tags:
              - Todo
            parameters:
              - name: id
                in: path
                required: true
                description: Parameter description in CommonMark or HTML.
                schema:
                  type: integer
                  format: int32
            responses:
              '200':
                description: Success
          put:
            tags:
              - Todo
            parameters:
              - name: id
                in: path
                required: true
                schema:
                  type: integer
                  format: int32
            requestBody:
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Todo'
                text/json:
                  schema:
                    $ref: '#/components/schemas/Todo'
                application/*+json:
                  schema:
                    $ref: '#/components/schemas/Todo'
            responses:
              '200':
                description: Success
          delete:
            tags:
              - Todo
            parameters:
              - name: id
                in: path
                required: true
                schema:
                  type: integer
                  format: int32
            responses:
              '200':
                description: Success
      components:
        schemas:
          Todo:
            type: object
            properties:
              id:
                type: integer
                format: int32
              name:
                type: string
                nullable: true
              isComplete:
                type: boolean
            additionalProperties: false
  lifecycle: experimental
  owner: ahemad
  type: openapi
