apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: poc-backstage-api
  description: The todos API
  tags:
    - todo
    - dot-net-core-web-api
  links:
    - url: https://github.com/ahemadpirzada-cloud/Backstage-API-Templates
      title: GitHub Repo
      icon: github
    - url: https://github.com/ahemadpirzada-cloud/Backstage-API-Templates/blob/main/todo.yaml
      title: API Spec
      icon: code
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: experimental
  owner: ahemadpirzada
  definition: |
    openapi: 3.0.1
    info:
      title: WebAPI
      version: '1.0'
    servers:
      - url: http://localhost:3080
    paths:
  "/todos":
    get:
      summary: Get all the tasks
      description: Get all the tasks
      produces:
      - application/json
      parameters: []
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              "$ref": "#/definitions/todosResponse"
        '400':
          description: Invalid status value
          schema:
            "$ref": "#/definitions/InvalidResponse"
  
