apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: poc-backstage-api
  description: The books API
  tags:
    - books
    - node-js-web-api
  links:
    - url: https://github.com/ahemadpirzada-cloud/Backstage-API-Templates
      title: GitHub Repo
      icon: github
    - url: https://github.com/ahemadpirzada-cloud/Backstage-API-Templates/blob/main/todo.yaml
      title: API Spec
      icon: code
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: experimental
  owner: ahemad
  definition: |
    openapi: 3.0.1
    info:
      title: WebAPI
      version: '1.0'
    servers:
      - url: http://localhost:8080
    paths:
      /books:
        get:
          tags:
            - books
          responses:
            '200':
              description: Success
        post:
          tags:
            - books
          requestBody:
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/books'
              text/json:
                schema:
                  $ref: '#/components/schemas/books'
              application/*+json:
                schema:
                  $ref: '#/components/schemas/books'
          responses:
            '200':
              description: Success
      /books:
        get:
          tags:
            - books
          responses:
            '200':
              description: Success
      '/api/books/{id}':
        get:
          tags:
            - Todo
          parameters:
            - name: id
              in: path
              required: true
              schema:
                type: string
          responses:
            '200':
              description: Success
        put:
          tags:
            - books
          parameters:
            - name: title
              in: path
              required: true
              schema:
                type: string
          requestBody:
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/books'
              text/json:
                schema:
                  $ref: '#/components/schemas/books'
              application/*+json:
                schema:
                  $ref: '#/components/schemas/books'
          responses:
            '200':
              description: Success
        delete:
          tags:
            - Todo
          parameters:
            - name: id
              in: path
              required: true
              schema:
                type: string
          responses:
            '200':
              description: Success
    components:
      schemas:
        Todo:
          type: object
          properties:
            title:
              type: string
              nullable:true
            id:
              type: integer
              format: int32
